# Generated by Django 3.1.4 on 2020-12-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movie', '0002_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movies',
            new_name='Movie',
        ),
    ]
